repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        exclude: |
          (?x)(
              \\.idea/(.)*|
              \\notebooks/(.)*|
              \\sample/(.)*|
          )
      - id: check-case-conflict
        exclude: |
          (?x)(
              \\.idea/(.)*|
              \\notebooks/(.)*|
              \\sample/(.)*|
          )
      - id: check-merge-conflict
        exclude: |
          (?x)(
              \\.idea/(.)*|
              \\notebooks/(.)*|
              \\sample/(.)*|
          )
      - id: debug-statements
        exclude: |
          (?x)(
              \\.idea/(.)*|
              \\notebooks/(.)*|
              \\sample/(.)*|
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              \\.idea/(.)*|
              \\notebooks/(.)*|
              \\sample/(.)*|
          )
      - id: trailing-whitespace
        exclude: |
          (?x)(
              \\.idea/(.)*|
              \\notebooks/(.)*|
              \\sample/(.)*|
          )

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        args: [--line-length=120]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        args: [--disable=MD013, --disable=MD033, --disable=MD050, --disable=MD052]
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.6.0.rc1
    hooks:
      - id: docformatter
        args: [--in-place]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.229"
    hooks:
      - id: ruff
  - repo: https://github.com/pycqa/pylint
    rev: "v2.16.0b1"
    hooks:
      - id: pylint
        exclude: "test_*"
        args: ["--unsafe-load-any-extension=y"]
        additional_dependencies:
          [
            picologging,
            pydantic,
            pylint-pydantic,
            jinja2,
            hiredis,
            passlib,
            rich,
            packaging,
            pydantic_factories,
            pydantic_openapi_schema,
            git+https://github.com/sqlalchemy/sqlalchemy,
            starlite-saqlalchemy,
            starlite_multipart,
            structlog,
            aiosmtplib,
            alembic,
            asyncpg,
            asyncpg-stubs,
            httpx,
            pytest,
            pytest-docker,
            saq,
            starlite,
            types-freezegun,
            types-python-jose,
            types-click,
            types-redis,
            types-passlib,
            types-click,
            uvicorn,
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        additional_dependencies:
          [
            picologging,
            pydantic,
            pylint-pydantic,
            jinja2,
            hiredis,
            passlib,
            rich,
            packaging,
            pydantic_factories,
            pydantic_openapi_schema,
            git+https://github.com/sqlalchemy/sqlalchemy,
            starlite-saqlalchemy,
            starlite_multipart,
            structlog,
            aiosmtplib,
            alembic,
            asyncpg,
            asyncpg-stubs,
            httpx,
            pytest,
            pytest-docker,
            saq,
            starlite,
            types-freezegun,
            types-python-jose,
            types-click,
            types-redis,
            types-passlib,
            types-click,
            uvicorn,
          ]
