# type: ignore
"""Add indexes

Revision ID: de594e3100c8
Revises: dc04c9afb20e
Create Date: 2024-11-08 09:34:17.097503+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = 'de594e3100c8'
down_revision = 'dc04c9afb20e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.create_index('idx_opportunity_tenant_id_created_at', ['tenant_id', sa.text('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('opportunity_job_post_relation', schema=None) as batch_op:
        batch_op.create_index('idx_opportunity_job_post_relation_opportunity_job', ['opportunity_id', 'job_post_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_job_post_relation', schema=None) as batch_op:
        batch_op.drop_index('idx_opportunity_job_post_relation_opportunity_job')

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_owner_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_company_id'))
        batch_op.drop_index('idx_opportunity_tenant_id_created_at')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
