# type: ignore
"""Add repo to icp and opportunity repo relation

Revision ID: fc8048732b16
Revises: 231be9e49e29
Create Date: 2024-12-29 17:10:30.829322+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

from app.db.models.custom_types import RepoCriteriaType

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "fc8048732b16"
down_revision = "231be9e49e29"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("icp", schema=None) as batch_op:
        batch_op.add_column(sa.Column("repo", RepoCriteriaType(), nullable=True))

    with op.batch_alter_table("opportunity_repo_relation", schema=None) as batch_op:
        batch_op.drop_index("idx_opportunity_repo_relation_opportunity_job")
        batch_op.create_index(
            "idx_opportunity_repo_relation_opportunity_repo", ["opportunity_id", "repo_id"], unique=False
        )

    with op.batch_alter_table("repo", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_repo_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_repo_name"), ["name"], unique=False)
        batch_op.create_index("ix_repo_slug_unique", ["slug"], unique=True)

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repo", schema=None) as batch_op:
        batch_op.drop_index("ix_repo_slug_unique")
        batch_op.drop_index(batch_op.f("ix_repo_name"))
        batch_op.drop_index(batch_op.f("ix_repo_company_id"))

    with op.batch_alter_table("opportunity_repo_relation", schema=None) as batch_op:
        batch_op.drop_index("idx_opportunity_repo_relation_opportunity_repo")
        batch_op.create_index(
            "idx_opportunity_repo_relation_opportunity_job", ["opportunity_id", "repo_id"], unique=False
        )

    with op.batch_alter_table("icp", schema=None) as batch_op:
        batch_op.drop_column("repo")

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
