# type: ignore
"""Make urls unique

Revision ID: db999dc8a9fd
Revises: 2a0170b3ad46
Create Date: 2024-08-30 15:51:51.651759+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "db999dc8a9fd"
down_revision = "2a0170b3ad46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_post", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_job_post_apply_url"), ["apply_url"])
        batch_op.create_unique_constraint(batch_op.f("uq_job_post_url"), ["url"])

    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_person_github_profile_url"), ["github_profile_url"])
        batch_op.create_unique_constraint(batch_op.f("uq_person_linkedin_profile_url"), ["linkedin_profile_url"])
        batch_op.create_unique_constraint(batch_op.f("uq_person_twitter_profile_url"), ["twitter_profile_url"])
        batch_op.create_unique_constraint(batch_op.f("uq_person_url"), ["url"])

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_person_url"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_person_twitter_profile_url"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_person_linkedin_profile_url"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_person_github_profile_url"), type_="unique")

    with op.batch_alter_table("job_post", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_job_post_url"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_job_post_apply_url"), type_="unique")

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
